config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},
                     :controllers => {:registrations => "registrations"}
  
  root to: 'pages#landing_page'

  resources :products

  resources :articles do
  resources :comments
  end

  resources :reviews

  resources :users, only: [:edit, :update, :show]

  get 'pages/landing_page'

  get '/contact' => "pages#contact"

  get '/about' => "pages#about"

  get 'form_input',   to: 'form_example#form_input'
  
  get 'form_output',  to: 'form_example#form_output'

  get 'contact_in',   to: 'contact#contact_in'
  
  get 'contact_out',  to: 'contact#contact_out'

  post 'payments/create'

  get 'payments/test_page'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
    if user.is_admin
      can :access, :rails_admin
      can :dashboard
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :description, length: { minimum: 20, maximum: 200 }
end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :name,  :presence => true
	validates :email, :presence => true,
	                  :format => /@/
	validates :text,  :length => { minimum: 5 }                  
end	

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable                              
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end 

  def create
    @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end  

  def update
    @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact_in
  end

  def contact_out
  	ActionMailer::Base.mail(:from => 'rogerrabbit_careerfoundry@yahoo.com', :to => 'spyrosfotiou@gmail.com', :subject => "Welcome to My Awesome Site", :body => 'I am the email body.').deliver
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
  	@featured_product = Product.find(1)
  end

  def contact
  end

  def about
  end
	
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end 

  def create
    @review = Review.new(review_params)
 
  if @review.save
    redirect_to @review
  else
    render 'new'
  end
  end

   def show
    @review = Review.find(params[:id])
  end

  def index
    debugger
    @reviews = Review.all
  end

  private
    def review_params
      params.require(:review).permit(:name, :email, :text)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  load_and_authorize_resource

  def show
 end

  def edit
  end

def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'The User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  

  private

  def user_params
    params.require(:user).permit( :email, :username, :age )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def cache_key_for_reviews
    count          = Review.count
    max_updated_at = Review.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "reviews/all-#{count}-#{max_updated_at}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Careerfoundry</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'pages/header' %> 

<%= yield %>

<%= render 'pages/footer' %> 


</body>
</html>

app/views/pages/_featured_product.html.erb
<div class="row feature">

      <div class="col-md-5">
        <%= image_tag @featured_product.image_url %>
      </div><!-- .col-md-5 -->

      <div class="col-md-7">
       <em><h2><small>Featured piece of clothing for the month, an original </small> <%= @featured_product.description %> <small> ,more info <%= link_to 'here', product_path(@featured_product) %> </small></h2> </em>
      </div><!-- .col-md-7 -->
    </div><!-- .row .feature -->  

<hr>    

app/views/pages/_footer.html.erb
<div class="container">
    <nav>
      <ul class="nav">
       <li><a href="privacy.html">Privacy</a><li>
       <li><a href="terms.html">Terms</a></li>
       <li><%= link_to 'FAQ', about_path %></li>
     </ul>
    </nav>
    <p>Copyright &copy; 2014 Medusa</p>
</div><!-- .container -->

app/views/pages/_header.html.erb
<div class="container">
  <nav>
  <ul class="nav">
     <% if user_signed_in? %>
    <li>You are logged in as <%= current_user.email %></li>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
    </ul>
    </nav>
</div>

<div class="container">
  
  <nav>
      <ul class="nav">
        <li><%= link_to 'Home', pages_landing_page_path %></li>
        <li><%= link_to 'Reviews', reviews_path %></li>
        <li><%= link_to 'Blog', articles_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><%= link_to 'All Products', products_path %></li>
      </ul>
    </nav>
    <a href="landing_page" id="landing"><%= image_tag "medusalogo.jpg" %></a>
</div>    

app/views/pages/about.html.erb
<h2>FAQ</h2>
<hr>

<div id="accordion" class="panel-group">

  <h2>Payment</h2>

  <div class="panel panel-default">
    <em><h4><a href="#collapse1" data-parent="#accordion" data-toggle="collapse">What credit cards do you accept?</a></h4></em>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body">
        <p>We accept all major credit cards plus paypal!</p>
      </div><!-- .panel-body -->
    </div><!-- .panel-collapse -->
  </div><!-- .panel -->

  <div class="panel panel-default">
    <em><h4><a href="#collapse2" data-parent="#accordion" data-toggle="collapse">Is there the option of a refund?</a></h4></em>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
        <p>No. We are running a small online business with a few unique pieces, therefore all sales are final.</p>
      </div><!-- .panel-body -->
    </div><!-- .panel-collapse -->
  </div><!-- .panel -->

  <hr>

  <h2>Delivery</h2>

  <div class="panel panel-default">
    <em><h4><a href="#collapse3" data-parent="#accordion" data-toggle="collapse">Where do you ship to?</a></h4></em>
    <div id="collapse3" class="panel-collapse collapse">
       <div class="panel-body">
        <p>Since we are only in the first stages, we are only shipping to Germany. However we are hoping to expand to EU soon!</p>
      </div><!-- .panel-body -->
    </div><!-- .panel-collapse -->
  </div><!-- .panel -->

  <div class="panel panel-default">
    <em><h4><a href="#collapse4" data-parent="#accordion" data-toggle="collapse">When will my order arrive?</a></h4></em>
    <div id="collapse4" class="panel-collapse collapse">
      <div class="panel-body">
        <p>All orders are sent the day after receiving your payment. You should expect it 3-5 working days after placing it. </p>
       </div><!-- .panel-body -->
    </div><!-- .panel-collapse -->
  </div><!-- .panel -->


</div><!-- #accordion -->

<hr>

app/views/pages/contact.html.erb
<div class="container">
    <h2>Contact</h2>
    <hr>
			<div class="row feature">
			<div class="col-md-7">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2430.316219206395!2d13.425799999999999!3d52.473409999999994!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a84f9652b00b77%3A0x7c2570fb1fd0cd95!2sLeinestra%C3%9Fe+8!5e0!3m2!1sen!2s!4v1398532026847" width="600" height="400" frameborder="0" style="border:0"></iframe>
			</div><!-- .col-md-7 -->
			<div class="col-md-5">
				<p> Medusa Clothing HQ: Leinestr. 8 12049 Berlin </p>
				



			</div><!-- .col-md-5 -->
		</div><!-- .row .feature -->
	</div>

  <hr>

  <div class="container">

<form action="#" method="post" id="contact-form">
  <h2>Form</h2>
  <p>If you have any questions or comments, contact us using the form below.</p>
  <p><label for="name">Name:</label><input type="text" name="name" id="name" placeholder="Full Name" required autofocus></p>
  <p><label for="email">Email:</label><input type="email" name="email" id="email" placeholder="email@example.com" required></p>
  <p><label for="website">Website:</label><input type="url" name="website" id="website" placeholder="www.example.com"></p>
  <p>
    <label for="category">Category:</label>
   <input type="radio" name="category" value="General" checked> General
<input type="radio" name="category" value="Sale"> Sale
<input type="radio" name="category" value="Shipment"> Shipment
  </p>

  <p>
    <label for="comment">Comment:</label>
    <textarea name="comment" id="comment" placeholder="Send us your comments"></textarea>
  </p>
    <p><label for="category">How did you hear about Medusa:</label>
   <input type="checkbox" name="category" value="Friend" checked> Friend
<input type="checkbox" name="category" value="Facebook"> Facebook
<input type="checkbox" name="category" value="Other"> Other
  </p>
  <p><input type="submit" value="Submit" class="btn btn-success"></p>
</form>
				
</div>

app/views/pages/landing_page.html.erb
<div class="container">
<h1>Welcome</h1>
<hr>
  <div id="owl-demo" class="owl-carousel owl-theme">
  <div> <%= image_tag "medusa01.jpg" %> </div>
  <div> <%= image_tag "medusa02.jpg" %> </div>
  <div> <%= image_tag "medusa03.jpg" %> </div>
  </div>

  <div class="container">
        <p><button type="button" class="btn btn-default btn-lg">Shop the collection now!</button></p>
      </div><!-- .container -->

   <script>


                    $(document).ready(function() {
 
  $("#owl-demo").owlCarousel({
 
      navigation : true, // Show next and prev buttons
      slideSpeed : 300,
      paginationSpeed : 400,
      singleItem:true
 
      // "singleItem:true" is a shortcut for:
      // items : 1, 
      // itemsDesktop : false,
      // itemsDesktopSmall : false,
      // itemsTablet: false,
      // itemsMobile : false
 
  });
 
});
        </script>

<hr>
<div class="row feature">
      <div class="col-md-7">
        <em><h2>Medusa Clothing <small>is the new kid in the Berlin Vintage Scene, collecting rare gems from the 80's, the 90's and beyond. Discover unique pieces in prices that can't be beat and don't forget to find us on <a href="https://www.facebook.com/medusafashion/">Facebook!</a> </small> </h2></em>
  

      </div><!-- .col-md-7 -->
      <div class="col-md-5">
        <%= image_tag "medusa1.jpg" %>
      </div><!-- .col-md-5 -->
    </div><!-- .row .feature -->  
<hr>

<% feat_prod = Product.find(1) %>

<%= render 'pages/featured_product' %>   

</div>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-name="Medusa"
  data-description="<%=@product.description%> (<%=@product.price%> €)"
  data-currency="EUR"
  data-amount="<%=(@product.price*100).to_i%>">
  
  </script>
  