config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},
                     :controllers => {:registrations => "registrations"}
  
  root to: 'pages#landing_page'

  resources :products

  resources :articles do
  resources :comments
  end

  resources :reviews

  resources :users, only: [:edit, :update, :show]

  get 'pages/landing_page'

  get '/contact' => "pages#contact"

  get '/about' => "pages#about"

  get 'form_input',   to: 'form_example#form_input'
  
  get 'form_output',  to: 'form_example#form_output'

  get 'contact_in',   to: 'contact#contact_in'
  
  get 'contact_out',  to: 'contact#contact_out'

  post 'payments/create'

  get 'payments/test_page'

  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end 

  def create
    @review = Review.new(review_params)
 
  if @review.save
    redirect_to @review
  else
    render 'new'
  end
  end

   def show
    @review = Review.find(params[:id])
  end

  def index
    debugger
    @reviews = Review.all
  end

  private
    def review_params
      params.require(:review).permit(:name, :email, :text)
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def cache_key_for_reviews
    count          = Review.count
    max_updated_at = Review.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "reviews/all-#{count}-#{max_updated_at}"
  end
end

app/views/reviews/index.html.erb
<div class="container">

<h2>All reviews</h2>
 
<%= link_to 'New review', new_review_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
  </tr>
 
<% cache(cache_key_for_reviews) do %> 
<% @reviews.each do |review| %>
  <% cache(review) do %>
  <tr>
    <td><%= review.name %></td>
    <td><%= review.text %></td>
  </tr>
<% end %>
<% end %>
<% end %>
</table>

</div>

app/views/reviews/new.html.erb
<div class="container">

<h2>Write your review about Medusa!</h2>

<%= form_for :review, url: reviews_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', reviews_path %>

</div>

app/views/reviews/show.html.erb
<div class="container">
  
 <p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>
 
<%= link_to 'Back to Reviews', reviews_path %>

</div>